Isolate IpfsClient/KuboClient implementation from Gateway into `noosphere_ipfs`
subconsciousnetwork/noosphere pull request #203
Opened 2023-01-20 00:26 UTC by jsantell

2023-01-20 18:27 UTC, cdata requested changes
This is awesome, thanks for doing this. There is also some red tape needed to integrate this with our Github Actions workflows for release. 

Some areas to look at: https://github.com/subconsciousnetwork/noosphere/blob/d741c8db401a3f491025b49c042c6055b1175f9f/.github/workflows/release.yaml#L26-L35

https://github.com/subconsciousnetwork/noosphere/blob/d741c8db401a3f491025b49c042c6055b1175f9f/release-please-config.json#L7-L21

2023-01-20 18:27 UTC, cdata commented on rust/noosphere-cli/src/native/commands/serve/gateway.rs
> +    ipfs_syndication::start_ipfs_syndication,
Let's just keep this `ipfs` unless we have an egregious name ambiguity

2023-01-20 18:27 UTC, cdata commented on rust/noosphere-ipfs/src/client.rs
> +    /// Returns the associated blocks (referenced by [Cid]) if found.
nit: Should be `block` singular, as the return value is always one block.

2023-01-20 18:27 UTC, cdata commented on rust/noosphere-ipfs/src/kubo.rs
> +        /*
Remove comment?

2023-01-20 18:27 UTC, cdata commented on rust/noosphere-ipfs/src/kubo.rs
> +        Err(anyhow!("not implemented"))
Prefer `todo!("What is to be done")`

2023-01-20 19:26 UTC, jsantell commented
Addressed feedback, fixed wasm tests; unsure about the expected return type of `IpfsClient::get(Cid)` until digging into the http RPC more

2023-01-20 19:38 UTC, jsantell commented on rust/README.md
> +rustup target add wasm32-unknown-unknown
Looks like rustup uses `add` now

2023-01-23 18:05 UTC, cdata approved these changes
Thanks for this refactor / cleanup!

2023-01-23 18:05 UTC, cdata commented on rust/README.md
> +rustup target add wasm32-unknown-unknown
Probably my typo TBH

2023-01-23 18:06 UTC, merged