feat: Initial integration of orb-ns CLI into the Name System's operator API
subconsciousnetwork/noosphere pull request #218
Opened 2023-02-02 19:31 UTC by jsantell

* Implements `orb-ns status`
* Implements `orb-ns records [(get $DID)|(put $RECORD)]`
* Implements `orb-ns peers [ls|(add $ADDR)]`
* Synchronizes orb-ns flags with the config file variant for bootstrap nodes
* Allow SocketAddr/Url/Multiaddr to be represented by SocketAddr/IpAddr/u16 Ports in orb-ns flags and configs.

2023-02-06 18:08 UTC, cdata commented
Recorded test flake for posterity, with commentary: https://github.com/subconsciousnetwork/noosphere/issues/167#issuecomment-1419528064

2023-02-06 18:14 UTC, cdata requested changes
This looks great; some light cleanup is requested.

2023-02-06 18:14 UTC, cdata commented on rust/noosphere-ns/src/bin/orb-ns/cli_address.rs
> +pub fn parse_cli_address<T: TryFrom<CLIAddress>>(input: &str) -> Result<T, String> {
Even if they are small, some member docs on these would be welcome

2023-02-06 18:14 UTC, cdata commented on rust/noosphere-ns/src/bin/orb-ns/main.rs
> +            println!("{:#?}", info);
Let's prefer `tracing::{info,debug,error,warn,trace}` to `println` throughout this change!

2023-02-06 19:08 UTC, jsantell commented
* Updated `println!` to `tracing::info!` note, these are a little sloppy at the moment -- future PR with full JSON responses for the "getter" cli commands (`orb-ns records get X`)
* Fixed module-docs, and added docs/doctests for some CLIAddress conversions

2023-02-06 19:13 UTC, jsantell commented
bin doctests are *not* run on `cargo test` -- looking into this

2023-02-06 21:06 UTC, jsantell commented
Ok updated and moved `CLIAddress` conversion tests to regular unit tests (so they run on `cargo run`), fixed some issues, and had to roll a de/serializersto handle both int and str types. Ready for one more pass!

2023-02-07 21:03 UTC, cdata approved these changes
Great work!

2023-02-07 21:03 UTC, merged