chore: Iterative updates to NameSystem/DHT as validation integrated and exposed throughout.
subconsciousnetwork/noosphere pull request #308
Opened 2023-04-10 19:58 UTC by jsantell

Iterative updates as #267 is being worked on in tests

* Propagate IPFS Client through Gateway workers.
* Use UcanJwtStore, rather than Custom Validator, for NameSystem configuration (fixes #268), though there is still currently an escape hatch for validation via None.
* Decouple sphere-esque mocks from NS bootstrapping networks in tests via `noosphere_ns::helpers::NameSystemNetwork`.
* Begin migration where DidParser is optional for `NsRecord::validate()`, and more specific errors during record validation.

2023-04-11 22:13 UTC, cdata requested changes
Nice cleanup, just a few small items to take care of :beers:

2023-04-11 22:26 UTC, jsantell commented on rust/noosphere-ns/Cargo.toml
> +thiserror = "^1"
100%

2023-04-11 22:26 UTC, jsantell commented on rust/noosphere-gateway/src/route/push.rs
> +            self.notify_ipfs_syndicator(next_version),
Nope, undoing

2023-04-12 15:38 UTC, cdata approved these changes
Woot!

2023-04-12 15:38 UTC, merged