feat: Enable support of quorum=0 for DHT during infra bootstrapping phase
subconsciousnetwork/noosphere pull request #335
Opened 2023-04-26 22:42 UTC by jsantell

* Decouple validity vs expiration in NsRecord::validate.
* Fixes #264, using response from name system server.
* Remove "local cache" from NameSystem, as its a bit dated and redundant with libp2p Kademlia storage, where persistence and validity should be handled.
* Rename s/NameSystemClient/DhtClient and separate p2p nature from the name resolver, via NameResolver trait (publish, resolve) for consumer usage (e.g. hiding those quorum rules from gateway).

2023-04-26 23:32 UTC, cdata requested changes
Looks good, just needs a little cleanup

2023-04-26 23:32 UTC, cdata commented on rust/noosphere-ns/src/name_system.rs
> +    DhtClient, NameResolver, PeerId,
Fix warning

2023-04-26 23:32 UTC, cdata commented on rust/noosphere-ns/tests/ns_test.rs
> -    NameSystemClient, NsRecord,
Fix warnings throughout

2023-04-26 23:50 UTC, jsantell commented
Rebased and lints fixed! Going through the tests once more

2023-04-27 17:10 UTC, cdata approved these changes

2023-04-27 17:10 UTC, merged