feat: validate link records on the gateway
subconsciousnetwork/noosphere pull request #338
Opened 2023-04-27 17:06 UTC by jsantell

2023-05-01 20:25 UTC, cdata requested changes
Mostly just name bike shedding, looks good!

2023-05-01 20:25 UTC, cdata commented on rust/noosphere-gateway/src/worker/syndication.rs
> +        match process_task(job, kubo_client.clone(), &ipfs_api).await {
Probably should work "job" into the name here, like `process_job`.

2023-05-01 20:25 UTC, cdata commented on rust/noosphere-gateway/src/worker/name_system.rs
> +                    let link_record = NsRecord::from_str(&record)?;
What are the chances we could get tests that cover the valid / invalid cases?

2023-05-01 20:28 UTC, jsantell commented on rust/noosphere-gateway/src/worker/syndication.rs
> +async fn ipfs_syndication_processor<C, K, S>(
SG! I'll change back to **task** a la Tokio, processing **jobs**

2023-05-04 16:36 UTC, jsantell commented
Dependent on https://github.com/ucan-wg/rs-ucan/pull/83

2023-05-05 16:57 UTC, jsantell commented
* Depends on #360 (ucan 0.2.0, validation that doesn't include expiry)
* Introduced `KeyValueNameResolver`, a simplified name resolver for unit tests
* Add a test for publishable timeframe for gateway, also illustrating how we can test individual job processing

2023-05-05 17:03 UTC, jsantell commented on rust/noosphere-gateway/src/worker/syndication.rs
No logic changes in this file, just copies the handling of `process_job()` like the NS worker

2023-05-05 17:03 UTC, jsantell commented on rust/noosphere-gateway/src/worker/name_system.rs
> +                if link_record.has_publishable_timeframe() {
This file is noisy due to restructuring processing: adding a publishable timeframe check here

2023-05-05 17:03 UTC, jsantell commented on rust/noosphere-gateway/src/worker/name_system.rs
>                  Some(record) => {
This file is noisy due to restructuring processing: adding validation check here

2023-05-05 17:03 UTC, jsantell commented on rust/noosphere-cli/tests/peer_to_peer.rs
>  use noosphere_storage::{BlockStoreRetry, MemoryStore, UcanStore};
Changes here are shared with #344

2023-05-05 18:44 UTC, jsantell commented
Put validation behind a flag for deployment so the validation doesn't yet actually occur, but can be reconciled with other NS work and enabled shortly in the future

2023-05-15 16:27 UTC, cdata commented
This looks good, but I just want to clarify that it doesn't fix #257 . In order to fix #257, we need to introduce validation here: https://github.com/subconsciousnetwork/noosphere/blob/14f7d61209ae975928cc3c24f1df1dc55a4427ff/rust/noosphere-sphere/src/petname/write.rs#L93-L94

Sorry, we should have had those TODOs annotated.

This addresses perhaps one half of the task, but really validation should be happening at this point where we try to write to the SphereContext, and it should probably be mostly symmetrical across any sphere mutation (be it the gateway's sphere, the user's sphere, or ....)

2023-05-15 16:28 UTC, cdata approved these changes
LGTM

2023-05-15 16:29 UTC, merged