[WIP] Task Workers
subconsciousnetwork/noosphere pull request #796
Opened 2024-01-24 19:53 UTC by jsantell

2024-02-01 19:37 UTC, jsantell commented
Added explicit checks on existence of name records after syncing changes in tests, possibly clearing up a handful of intermittent failures.

Windows builds are having an unrelated issue: https://github.com/subconsciousnetwork/noosphere/pull/805

2024-02-05 22:42 UTC, jsantell commented on rust/noosphere-gateway/src/single_tenant/job_client.rs
> +const TIMEOUT_SECONDS: u64 = 180;
Syndicating large histories could be longer than this timeout, and notably, name records' publishing timeframe is currently 2 minutes.

2024-02-26 18:44 UTC, cdata requested changes
The bones look excellent, but I have some light opinions about some of the flesh :)

Great work so far!

2024-02-26 18:44 UTC, cdata commented on rust/noosphere-gateway/src/jobs/worker_queue/queue.rs
> +            let workers = WorkerQueueThread::<P>::new(
The naming and documentation were confusing to read the first time around. `WorkerQueue` sounds like "the thing that has a pool of workers." In fact, the documentation currently reads:

```rs
/// An abstraction around managing several worker threads, and distributing
/// work amongst them.
```

And, there is `WorkerQueueThread`, which sounds like the thing that does work on a thread. But, most of the meaningful management of multiple threads is performed by `WorkerQueueThread`.

Why are these separate constructs? It kind of looks like all that `WorkerQueue` does is thinly wrap `WorkerQueueThread`. Also: can we call `WorkerQueueThread` something closer to what it is? Maybe it's just `WorkerQueue`, maybe it's a `WorkerQueuePool`. It's certainly not a single thread so long as it has a `Vec<Workers<P>>`.

2024-02-26 18:44 UTC, cdata commented on rust/noosphere-gateway/src/jobs/worker_queue/worker.rs
> +/// on another thread.
Can you comment about the usage and lifecycle of a `Worker` in the documentation?

2024-02-26 18:44 UTC, cdata commented on rust/noosphere/tests/distributed_basic.rs
> +    {
Why is the extra block needed?

2024-02-26 19:59 UTC, jsantell commented on rust/noosphere/tests/distributed_basic.rs
> +    {
Looks unnecessary, will remove

2024-02-27 16:05 UTC, jsantell commented
Updates ([commit](https://github.com/subconsciousnetwork/noosphere/pull/796/commits/8cadcfc18fb9e514ebf7d4426bd97bda06476e11)):
* Changes/cleanups from feedback
* Remove vestigial `revision` in IpfsSyndication job
* Reduce indirection from cloning (e.g. use outer Arcs, not inner)
* s/ContextResolver/SphereContextResolver
* s/NameResolverExt/NameResolverPoller
* s/WorkerQueueThread/WorkerQueueOrchestrator
* More documentation for `worker_queue`

2024-02-29 17:32 UTC, cdata approved these changes
LGTM, thanks for the hard work on this!

2024-02-29 18:27 UTC, merged